import { actions, getState, setState } from '../src/store';
import { syncNow, verifyAccount } from '../src/sync';
const B = 'http://127.0.0.1:8787';
const post = async (p: string, body: any, token?: string, method = 'POST') => { const r = await fetch(B + p, { method, headers: { 'content-type': 'application/json', ...(token ? { authorization: 'Bearer ' + token } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { s: r.status, j: await r.json().catch(() => null) as any }; };
const ok = (c: any, m: string) => { if (!c) { console.log('FAIL', m); process.exit(1); } console.log('ok', m); };
const a = await post('/api/auth/register', { email: 'Sera@Example.com', password: 'password123' });
ok(a.s === 201 && a.j.user.isAdmin, 'first user admin');
ok((await post('/api/auth/register', { email: 'b@x.com', password: 'password123' })).s === 403, 'registration closed');
ok((await post('/api/auth/login', { email: 'sera@example.com', password: 'wrong' })).s === 401, 'wrong pw');
const l = await post('/api/auth/login', { email: 'sera@example.com', password: 'password123', kind: 'app' });
ok(l.s === 200, 'login');
const v = await verifyAccount(a.j.token, B, 'data');
ok(v.login === 'sera@example.com' && v.isPrivate, 'github-compat verify');
actions.updateSync({ token: a.j.token, owner: B, repo: 'data', login: v.login });
actions.upsertTask(actions.newTask({ title: '中文 task 🐧' }));
let r = await syncNow(); ok(r.uploaded, 'web upload to server');
// "app" token syncs as a second device
setState((s) => ({ ...s, tasks: [], syncBase: { account: '', ids: {} } }), false);
actions.updateSync({ token: l.j.token });
r = await syncNow(); ok(getState().tasks.some((t) => t.title === '中文 task 🐧'), 'second device pulls');
const ov = await post('/api/admin/overview', null, a.j.token, 'GET');
ok(ov.s === 200 && ov.j.users[0].data_size > 0 && JSON.parse(ov.j.users[0].counts).tasks === 1, 'admin overview');
ok((await post('/api/admin/settings', { registrationOpen: true }, a.j.token)).s === 200, 'open reg');
const b = await post('/api/auth/register', { email: 'b@x.com', password: 'password123' });
ok(b.s === 201 && !b.j.user.isAdmin, 'second user normal');
ok((await post('/api/admin/overview', null, b.j.token, 'GET')).s === 403, 'non-admin blocked');
const g = await fetch(B + '/repos/me/data/contents/penguinbrain-sync.json', { headers: { authorization: 'Bearer ' + b.j.token } });
ok(g.status === 404, 'data isolated per user');
ok((await post('/api/admin/users/2', { disabled: true }, a.j.token, 'PATCH')).s === 200, 'disable');
ok((await post('/api/auth/me', null, b.j.token, 'GET')).s === 401, 'disabled token revoked');
const bad = await fetch(B + '/repos/me/data/contents/x', { method: 'PUT', headers: { authorization: 'Bearer ' + a.j.token }, body: JSON.stringify({ content: btoa('{}'), sha: 'wrong' }) });
ok(bad.status === 409, 'conflict 409');
console.log('E2E PASSED');
